services:
  informaticsge:
    container_name: informatics
    build:
      context: .
      dockerfile: informaticsge/Dockerfile
    restart: on-failure
    networks:
      - backend
      - compilation
    ports:
      - 5276:5276
      
  compilation-service:
    container_name: compilation-service
    build:
      context: .
      dockerfile: Compilation-Service/Dockerfile
    restart: always
    networks:
      - compilation
    ports:
      - 5144:5144
    
  Postgres.Db:
    image: postgres:latest
    container_name: PostgresDb
    environment: 
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    restart: always
    networks:
      - backend
    ports:
      - 5432:5432
    volumes: 
      - database:/var/lib/postgresql/data

    
volumes:
  database:


networks:
  compilation:
  backend: