namespace Compilation_Service.Dto.Response;

public class SubmissionResponseDto
{

    public bool Success { get; set; }
    public string? Input { set; get; }
    public string? ExpectedOutput { set; get; }
    public string? Output { get; set; } // Output generated by the compiled code
    public string? Status { get; set; }

}