namespace BuildingBlocks.Common.Classes;

public class TestResultDto
{
    public bool Success { get; set; }
    public string? Input { set; get; }
    public string? ExpectedOutput { set; get; }
    public string? Output { get; set; } // Output generated by the compiled code
    public string? Status { get; set; }

}