# This is a generated file. Not intended for manual editing.
version: "3.8"
services:
  migrator:
    build:
      context: "C:\\Users\\kaxaq\\RiderProjects\\LeetCode-Clone-with-.NET-8.0"
      dockerfile: "Services/MainApp/MainApp.Migrations/Dockerfile"
      target: "build"
    command: []
    entrypoint:
    - "dotnet"
    - "/app/bin/Debug/net8.0/MainApp.Migrations.dll"
    environment:
      ASPNETCORE_ENVIRONMENT: "Development"
    image: "mainapp.migrations:dev"
    ports: []
    volumes:
    - "C:\\Users\\kaxaq\\RiderProjects\\LeetCode-Clone-with-.NET-8.0\\Services\\MainApp\\\
      MainApp.Migrations:/app:rw"
    - "C:\\Users\\kaxaq\\RiderProjects\\LeetCode-Clone-with-.NET-8.0:/src:rw"
    - "C:\\Users\\kaxaq\\.nuget\\packages:/root/.nuget/packages"
    working_dir: "/app"
