namespace informaticsge.models;

public class CompilationResult
{

    public bool Success { get; set; }
    public string? Error { get; set; }
    public string? Output { get; set; } // Output generated by the compiled code
}