name: CI/CD Pipeline

on:
  push:
    branches:
      - adding-CICD

jobs:
  build-and-push:
    name: Build & Push Docker Images
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout code
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Log in to Docker Hub
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # Step 3: Build and push images
      - name: Build and Push Docker Compose Services
        working-directory: ./src/
        run: |
          docker compose -f docker-compose.yml build
          docker compose -f docker-compose.yml push

  deploy:
    name: Deploy on Server
    runs-on: ubuntu-latest
    needs: build-and-push   # ensures this job runs after images are built & pushed

    steps:
      # Step 1: SSH & Deploy
      - name: SSH & Deploy Docker Compose
        uses: appleboy/ssh-action@v0.1.6
        with:
          host: ${{ secrets.SERVER_IP }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            echo "Deploying project..."
            cd ~/leetcode-clone                # server project folder
            docker compose pull              # pull updated images from Docker Hub
            docker compose down              # stop old containers
            docker compose up -d             # start containers with new images
            echo "Deployment finished!"